"use client";

import { useState, useEffect, useRef } from "react";
import { Trash2, Code2, Send, Loader2, Wand2, Check, Settings, Plus } from "lucide-react";
import CodeMirror from "@uiw/react-codemirror";
import { javascript } from "@codemirror/lang-javascript";
import { vscodeDark } from "@uiw/codemirror-theme-vscode";
import type { Overlay } from "@/overlays";
import { useTheme } from "@/hooks/useTheme";
import { useAnimationChat } from "@/hooks/useAnimationChat";
import { AskQuestion } from "./AskQuestion";
import type { MediaItem } from "./LeftPanel";
import { parseConfig, updateConfigValue, parseDurationFrames } from "@/lib/parseConfig";

interface Props {
  overlay: Overlay | null;
  onUpdate: (data: Partial<Overlay>) => void;
  onRemove: () => void;
  media?: MediaItem[];
  onAddLayer?: () => void;
}

type Tab = "chat" | "settings" | "code";

const SUGGESTIONS = [
  { label: "Subscribe counter", prompt: "YouTube-style subscribe button with animated follower count that ticks up from 999K to 1M" },
  { label: "Typing text", prompt: "Typewriter effect that types out 'Coming Soon...' with a blinking cursor" },
  { label: "Notification", prompt: "macOS-style notification that slides in from top-right with app icon and message" },
  { label: "Logo reveal", prompt: "Animated logo reveal with particles that converge into the center and form a glowing icon" },
  { label: "Progress bar", prompt: "Animated progress bar that fills from 0% to 100% with a glowing effect" },
  { label: "Countdown", prompt: "Countdown timer from 10 to 0 with each number animating in and out" },
];

const tabs: { id: Tab; label: string; icon: React.ReactNode }[] = [
  { id: "chat", label: "Generate", icon: <Wand2 size={12} /> },
  { id: "settings", label: "Settings", icon: <Settings size={12} /> },
  { id: "code", label: "Code", icon: <Code2 size={12} /> },
];

export function RightPanel({ overlay, onUpdate, onRemove, media = [], onAddLayer }: Props) {
  const { theme } = useTheme();
  const [activeTab, setActiveTab] = useState<Tab>("chat");
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const hasAutoGenerated = useRef<string | null>(null);

  const { messages, input: chatInput, setInput: setChatInput, handleSubmit, isLoading, sendMessage, answerQuestion } = useAnimationChat({
    onCodeGenerated: (code) => {
      if (!overlay) return;
      const updates: Partial<Overlay> = { code };
      const duration = parseDurationFrames(code);
      if (duration) {
        updates.endFrame = overlay.startFrame + duration;
      }
      onUpdate(updates);
    },
    currentCode: overlay?.code,
    media: media,
    messages: overlay?.messages ?? [],
    onMessagesChange: (messages) => onUpdate({ messages }),
  });

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  // Auto-generate when created with a prompt
  useEffect(() => {
    if (overlay?.prompt && !overlay.code && hasAutoGenerated.current !== overlay.id) {
      hasAutoGenerated.current = overlay.id;
      sendMessage(overlay.prompt);
    }
  }, [overlay?.id, overlay?.prompt, overlay?.code, sendMessage]);

  // Reset tab when overlay changes
  useEffect(() => {
    if (!overlay?.code) setActiveTab("chat");
  }, [overlay?.id, overlay?.code]);

  // Empty state when no layer selected
  if (!overlay) {
    return (
      <div className="w-96 border-l border-zinc-200 dark:border-white/5 bg-zinc-50 dark:bg-zinc-900/50 flex flex-col overflow-hidden">
        <div className="flex-1 flex flex-col items-center justify-center p-6 text-center">
          <div className="w-12 h-12 rounded-full bg-zinc-100 dark:bg-zinc-800 flex items-center justify-center mb-4">
            <Wand2 size={20} className="text-zinc-400" />
          </div>
          <h3 className="text-sm font-medium text-zinc-700 dark:text-zinc-300 mb-1">No layer selected</h3>
          <p className="text-xs text-zinc-500 mb-4">Select a layer to edit or create a new one</p>
          {onAddLayer && (
            <button
              onClick={onAddLayer}
              className="px-3 py-1.5 text-xs bg-indigo-500 hover:bg-indigo-600 text-white rounded-lg transition-colors"
            >
              + New Layer
            </button>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="w-96 border-l border-zinc-200 dark:border-white/5 bg-zinc-50 dark:bg-zinc-900/50 flex flex-col overflow-hidden">
      {/* Header with tabs */}
      <div className="border-b border-zinc-200 dark:border-white/5 shrink-0">
        <div className="h-10 flex items-center justify-between px-3">
          <div className="flex gap-1">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex items-center gap-1.5 px-2.5 py-1 text-xs rounded-md transition-colors ${
                  activeTab === tab.id
                    ? "border border-indigo-500 text-zinc-900 dark:text-white"
                    : "border border-transparent text-zinc-500 hover:text-zinc-700 dark:hover:text-zinc-300"
                }`}
              >
                {tab.icon}
                {tab.label}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-1">
            {onAddLayer && (
              <button
                onClick={onAddLayer}
                className="text-zinc-400 hover:text-zinc-900 dark:hover:text-white p-1 rounded transition-colors"
                title="New layer"
              >
                <Plus size={14} />
              </button>
            )}
            <button
              onClick={onRemove}
              className="text-zinc-400 hover:text-red-500 p-1 rounded transition-colors"
              title="Delete layer"
            >
              <Trash2 size={14} />
            </button>
          </div>
        </div>
      </div>

      {/* Tab Content */}
      <div className="flex-1 overflow-hidden flex flex-col">
        {activeTab === "code" && (
          <div className="flex-1 overflow-auto">
            {overlay.code ? (
              <CodeMirror
                value={overlay.code}
                height="100%"
                theme={theme === "dark" ? vscodeDark : undefined}
                extensions={[javascript({ jsx: true, typescript: true })]}
                onChange={(value) => onUpdate({ code: value })}
                basicSetup={{
                  lineNumbers: true,
                  foldGutter: false,
                  dropCursor: false,
                  allowMultipleSelections: false,
                  indentOnInput: false,
                }}
                style={{ fontSize: 11 }}
              />
            ) : (
              <div className="flex-1 flex items-center justify-center text-zinc-400 text-sm p-4">
                <p>Use the AI tab to generate code</p>
              </div>
            )}
          </div>
        )}

        {activeTab === "settings" && (
          <div className="flex-1 overflow-y-auto p-3">
            {overlay.code ? (
              (() => {
                const config = parseConfig(overlay.code);
                if (config.length === 0) {
                  return (
                    <div className="text-center text-zinc-400 text-xs pt-4">
                      No configurable settings found in code
                    </div>
                  );
                }
                return (
                  <div className="space-y-3">
                    {config.map((entry) => (
                      <div key={entry.key}>
                        <label className="block text-[10px] text-zinc-500 mb-1">
                          {entry.key}
                        </label>
                        {entry.type === "color" ? (
                          <div className="flex items-center gap-2">
                            <input
                              type="color"
                              value={entry.value as string}
                              onChange={(e) => {
                                const newCode = updateConfigValue(overlay.code, entry.key, e.target.value);
                                onUpdate({ code: newCode });
                              }}
                              className="w-8 h-8 rounded border border-zinc-200 dark:border-zinc-700 cursor-pointer"
                            />
                            <input
                              type="text"
                              value={entry.value as string}
                              onChange={(e) => {
                                const newCode = updateConfigValue(overlay.code, entry.key, e.target.value);
                                onUpdate({ code: newCode });
                              }}
                              className="flex-1 px-2 py-1.5 text-xs bg-zinc-100 dark:bg-zinc-800 rounded border-0 outline-none focus:ring-1 focus:ring-indigo-500"
                            />
                          </div>
                        ) : entry.type === "number" ? (
                          <input
                            type="number"
                            value={entry.value as number}
                            onChange={(e) => {
                              const newCode = updateConfigValue(overlay.code, entry.key, parseFloat(e.target.value) || 0);
                              onUpdate({ code: newCode });
                            }}
                            className="w-full px-2 py-1.5 text-xs bg-zinc-100 dark:bg-zinc-800 rounded border-0 outline-none focus:ring-1 focus:ring-indigo-500"
                          />
                        ) : (
                          <input
                            type="text"
                            value={entry.value as string}
                            onChange={(e) => {
                              const newCode = updateConfigValue(overlay.code, entry.key, e.target.value);
                              onUpdate({ code: newCode });
                            }}
                            className="w-full px-2 py-1.5 text-xs bg-zinc-100 dark:bg-zinc-800 rounded border-0 outline-none focus:ring-1 focus:ring-indigo-500"
                          />
                        )}
                      </div>
                    ))}
                  </div>
                );
              })()
            ) : (
              <div className="text-center text-zinc-400 text-xs pt-4">
                Generate an animation first to configure settings
              </div>
            )}
          </div>
        )}

        {activeTab === "chat" && (
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Chat Messages */}
            <div className="flex-1 overflow-y-auto p-3 space-y-3">
              {messages.length === 0 && (
                <div className="space-y-3">
                  <div className="text-center pt-2">
                    <p className="text-xs text-zinc-500">
                      Describe your animation or pick a template
                    </p>
                  </div>

                  {/* Suggestions as chips */}
                  <div className="flex flex-wrap gap-1.5">
                    {SUGGESTIONS.map((suggestion) => (
                      <button
                        key={suggestion.label}
                        onClick={() => setChatInput(suggestion.prompt)}
                        className="px-2.5 py-1.5 text-[11px] rounded-full bg-zinc-100 dark:bg-zinc-800 hover:bg-indigo-500 hover:text-white text-zinc-600 dark:text-zinc-400 transition-colors"
                      >
                        {suggestion.label}
                      </button>
                    ))}
                  </div>

                  {media.length > 0 && (
                    <p className="text-[10px] text-zinc-400 text-center">
                      Tip: Reference your media by name in the prompt
                    </p>
                  )}
                </div>
              )}

              {messages.map((message, index) => {
                const isLastMessage = index === messages.length - 1;
                const isStreamingThis = isLoading && isLastMessage && message.role === "assistant";

                if (message.role === "question" && message.questionData) {
                  return (
                    <div key={message.id} className="mr-4">
                      <AskQuestion
                        header={message.questionData.header}
                        question={message.questionData.question}
                        options={message.questionData.options}
                        onSelect={(option) => answerQuestion(message.id, option)}
                        disabled={isLoading || message.answered || !isLastMessage}
                      />
                    </div>
                  );
                }

                return message.role === "user" ? (
                  <div
                    key={message.id}
                    className="ml-6 border border-indigo-500 text-zinc-900 dark:text-white rounded-xl rounded-tr-sm p-2.5 text-xs"
                  >
                    {message.content}
                  </div>
                ) : (
                  <div key={message.id} className="text-[11px] text-zinc-500 dark:text-zinc-400">
                    {isStreamingThis ? (
                      <span className="flex items-center gap-1.5">
                        <span className="animate-pulse">Generating</span>
                        <span className="flex gap-0.5">
                          <span className="w-1 h-1 bg-zinc-400 rounded-full animate-bounce" style={{ animationDelay: "0ms" }} />
                          <span className="w-1 h-1 bg-zinc-400 rounded-full animate-bounce" style={{ animationDelay: "150ms" }} />
                          <span className="w-1 h-1 bg-zinc-400 rounded-full animate-bounce" style={{ animationDelay: "300ms" }} />
                        </span>
                      </span>
                    ) : message.content.includes("```tsx") ? (
                      <span className="flex items-center gap-1">
                        <Check size={12} className="text-zinc-400" />
                        Generated
                      </span>
                    ) : (
                      <span className="whitespace-pre-wrap">{message.content}</span>
                    )}
                  </div>
                );
              })}

              <div ref={messagesEndRef} />
            </div>

            {/* Chat Input */}
            <form onSubmit={handleSubmit} className="p-3 border-t border-zinc-200 dark:border-zinc-800">
              <div className="relative">
                <textarea
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && !e.shiftKey) {
                      e.preventDefault();
                      if (chatInput.trim() && !isLoading) {
                        handleSubmit(e);
                      }
                    }
                  }}
                  placeholder="Describe animation..."
                  rows={3}
                  className="w-full px-3 py-2 pr-12 text-xs bg-zinc-100 dark:bg-zinc-800 rounded-lg border-0 focus:ring-1 focus:ring-indigo-500 outline-none resize-none"
                  disabled={isLoading}
                />
                <button
                  type="submit"
                  disabled={isLoading || !chatInput.trim()}
                  className="absolute right-2 bottom-2 p-1.5 bg-indigo-500 hover:bg-indigo-600 disabled:opacity-50 text-white rounded-md transition-colors"
                >
                  {isLoading ? <Loader2 size={14} className="animate-spin" /> : <Send size={14} />}
                </button>
              </div>
            </form>
          </div>
        )}
      </div>
    </div>
  );
}
