"use client";

import { useState, useEffect, useRef } from "react";
import { Trash2, Settings, Code2, Sparkles, Send, Loader2, Type, Image, Video, Zap } from "lucide-react";
import CodeMirror from "@uiw/react-codemirror";
import { javascript } from "@codemirror/lang-javascript";
import { vscodeDark } from "@uiw/codemirror-theme-vscode";
import { Toggle } from "./ui/toggle";
import { getOverlayDefinition, type Overlay } from "@/overlays";
import { useTheme } from "@/hooks/useTheme";
import { useAnimationChat } from "@/hooks/useAnimationChat";
import type { MediaItem } from "./LeftPanel";

interface Props {
  overlay: Overlay;
  onUpdate: (data: Partial<Overlay>) => void;
  onRemove: () => void;
  media?: MediaItem[];
}

type Tab = "properties" | "code" | "chat";

const SUGGESTIONS = [
  { label: "Text animation", icon: Type, prompt: "Large white text that says 'Hello World' centered on screen with a fade-in animation" },
  { label: "Image with zoom", icon: Image, prompt: "Display an image centered with a subtle zoom-in animation" },
  { label: "Video background", icon: Video, prompt: "Full-screen video background with a fade-in effect" },
  { label: "Bouncing ball", icon: Zap, prompt: "A colorful bouncing ball animation that bounces across the screen" },
];

const tabs: { id: Tab; label: string; icon: React.ReactNode }[] = [
  { id: "properties", label: "Properties", icon: <Settings size={12} /> },
  { id: "code", label: "Code", icon: <Code2 size={12} /> },
  { id: "chat", label: "AI", icon: <Sparkles size={12} /> },
];

export function RightPanel({ overlay, onUpdate, onRemove, media = [] }: Props) {
  const { theme } = useTheme();
  const definition = getOverlayDefinition(overlay.type);
  const [activeTab, setActiveTab] = useState<Tab>("chat");
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const hasAutoGenerated = useRef<string | null>(null);

  const { messages, input: chatInput, setInput: setChatInput, handleSubmit, isLoading, sendMessage } = useAnimationChat({
    onCodeGenerated: (code) => onUpdate({ code }),
    currentCode: overlay.code,
    media: media,
  });

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  // Auto-generate when created with a prompt
  useEffect(() => {
    if (overlay.prompt && !overlay.code && hasAutoGenerated.current !== overlay.id) {
      hasAutoGenerated.current = overlay.id;
      sendMessage(overlay.prompt);
    }
  }, [overlay, sendMessage]);

  // Reset tab when overlay changes
  useEffect(() => {
    if (!overlay.code) {
      setActiveTab("chat");
    }
  }, [overlay.id, overlay.code]);

  return (
    <div className="w-80 border-r border-zinc-200 dark:border-white/5 bg-zinc-50 dark:bg-zinc-900/50 flex flex-col overflow-hidden">
      {/* Header with tabs */}
      <div className="border-b border-zinc-200 dark:border-white/5 shrink-0">
        <div className="h-10 flex items-center justify-between px-3">
          <div className="flex gap-1">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex items-center gap-1.5 px-2.5 py-1 text-xs rounded-md transition-colors ${
                  activeTab === tab.id
                    ? "bg-zinc-200 dark:bg-white/15 text-zinc-900 dark:text-white"
                    : "text-zinc-500 hover:text-zinc-700 dark:hover:text-zinc-300"
                }`}
              >
                {tab.icon}
                {tab.label}
              </button>
            ))}
          </div>
          <button
            onClick={onRemove}
            className="text-zinc-400 hover:text-red-500 p-1 rounded transition-colors"
            title="Delete layer"
          >
            <Trash2 size={14} />
          </button>
        </div>
      </div>

      {/* Tab Content */}
      <div className="flex-1 overflow-hidden flex flex-col">
        {activeTab === "properties" && (
          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            {/* Type + Glass toggle */}
            <div className="flex items-center justify-between">
              <span className="text-xs text-zinc-500 uppercase tracking-widest">{overlay.type}</span>
              <Toggle
                size="sm"
                pressed={overlay.glass || false}
                onPressedChange={(pressed) => onUpdate({ glass: pressed })}
                className="h-6 px-2 text-[10px] text-zinc-500 data-[state=on]:bg-zinc-200 dark:data-[state=on]:bg-white/20 data-[state=on]:text-zinc-900 dark:data-[state=on]:text-white"
              >
                Glass
              </Toggle>
            </div>

            {/* Type-specific editor */}
            {definition?.editor({ overlay })}
          </div>
        )}

        {activeTab === "code" && (
          <div className="flex-1 overflow-auto">
            {overlay.code ? (
              <CodeMirror
                value={overlay.code}
                height="100%"
                theme={theme === "dark" ? vscodeDark : undefined}
                extensions={[javascript({ jsx: true, typescript: true })]}
                onChange={(value) => onUpdate({ code: value })}
                basicSetup={{
                  lineNumbers: true,
                  foldGutter: false,
                  dropCursor: false,
                  allowMultipleSelections: false,
                  indentOnInput: false,
                }}
                style={{ fontSize: 11 }}
              />
            ) : (
              <div className="flex-1 flex items-center justify-center text-zinc-400 text-sm p-4">
                <p>Use the AI tab to generate code</p>
              </div>
            )}
          </div>
        )}

        {activeTab === "chat" && (
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Chat Messages */}
            <div className="flex-1 overflow-y-auto p-3 space-y-3">
              {messages.length === 0 && (
                <div className="space-y-3">
                  <div className="text-center pt-4 pb-2">
                    <Sparkles size={20} className="mx-auto mb-2 text-violet-500" />
                    <p className="text-xs text-zinc-500">
                      Describe the animation you want
                    </p>
                  </div>

                  {/* Suggestions */}
                  <div className="space-y-1.5">
                    {SUGGESTIONS.map((suggestion) => (
                      <button
                        key={suggestion.label}
                        onClick={() => setChatInput(suggestion.prompt)}
                        className="w-full flex items-center gap-2.5 p-2.5 rounded-lg bg-zinc-100 dark:bg-zinc-800 hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors text-left group"
                      >
                        <div className="p-1.5 rounded-md bg-violet-500/10 text-violet-500">
                          <suggestion.icon size={14} />
                        </div>
                        <span className="text-xs text-zinc-600 dark:text-zinc-300 group-hover:text-zinc-900 dark:group-hover:text-white">
                          {suggestion.label}
                        </span>
                      </button>
                    ))}
                  </div>

                  {media.length > 0 && (
                    <p className="text-[10px] text-zinc-400 text-center pt-2">
                      Tip: Reference your media by name in the prompt
                    </p>
                  )}
                </div>
              )}

              {messages.map((message) => (
                <div
                  key={message.id}
                  className={`${
                    message.role === "user"
                      ? "ml-6 bg-violet-500 text-white rounded-xl rounded-tr-sm"
                      : "mr-6 bg-zinc-200 dark:bg-zinc-800 rounded-xl rounded-tl-sm"
                  } p-2.5 text-xs`}
                >
                  {message.role === "assistant" ? (
                    message.content.includes("```tsx") ? (
                      <span className="text-green-600 dark:text-green-400 flex items-center gap-1">
                        <Sparkles size={12} />
                        Code generated!
                      </span>
                    ) : (
                      <span className="whitespace-pre-wrap">{message.content}</span>
                    )
                  ) : (
                    message.content
                  )}
                </div>
              ))}

              {isLoading && (
                <div className="mr-6 bg-zinc-200 dark:bg-zinc-800 rounded-xl rounded-tl-sm p-2.5">
                  <Loader2 size={14} className="animate-spin text-zinc-400" />
                </div>
              )}

              <div ref={messagesEndRef} />
            </div>

            {/* Chat Input */}
            <form onSubmit={handleSubmit} className="p-3 border-t border-zinc-200 dark:border-zinc-800">
              <div className="flex gap-2">
                <input
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  placeholder="Describe animation..."
                  className="flex-1 px-3 py-2 text-xs bg-zinc-100 dark:bg-zinc-800 rounded-lg border-0 focus:ring-1 focus:ring-violet-500 outline-none"
                  disabled={isLoading}
                />
                <button
                  type="submit"
                  disabled={isLoading || !chatInput.trim()}
                  className="p-2 bg-violet-500 hover:bg-violet-600 disabled:opacity-50 text-white rounded-lg transition-colors"
                >
                  {isLoading ? <Loader2 size={14} className="animate-spin" /> : <Send size={14} />}
                </button>
              </div>
            </form>
          </div>
        )}
      </div>
    </div>
  );
}
